# Generated by Skyramp v1.2.0+c41d98f4 on 2026-03-14 10:08:55.211204 -0700 PDT m=+163.501479417
# Command: skyramp generate contract rest http://localhost:8000/api/v1/projects/1/features/summary/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_feature_summary.py \
# 		--output-dir /Users/mrugeshmaster/git/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
import requests
from skyramp import MockV2


# URL for test requests
URL = "http://localhost:8000"

# contract test for /api/v1/projects/1/features/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/projects/1/features/summary/",
        method="GET",
        status_code=200
    )
    client.apply_mock(mock)

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v1/projects/1/features/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(summary_GET_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_summary_get()
