# Generated by Skyramp v1.3.11 on 2026-03-11 13:16:19.525246297 +0000 UTC m=+215.201098589
# Command: skyramp generate fuzz rest http://localhost:8080/api/v1/budgets/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_budget_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--request-data {"feature":1,"evaluation_limit":1000,"limit_exceeded_action":"alert","reset_date":"2026-04-01"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# fuzz test for /api/v1/budgets/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
      "feature": 1,
      "evaluation_limit": 1000,
      "limit_exceeded_action": "alert",
      "reset_date": "2026-04-01"
    }'''
    
    # Fuzz strategies
    endpoint_post_fuzzed_body = {
        "evaluation_limit": -10,
        "feature": -10,
        "limit_exceeded_action": "0123456789",
        "reset_date": "0123456789"
    }
    # Fuzz status codes
    expected_endpoint_post_status_code = {
        "evaluation_limit": "40x",
        "feature": "40x",
        "limit_exceeded_action": "40x",
        "reset_date": "40x"
    }
    # Fuzz status codes for Null values
    expected_endpoint_post_null_status_code = {
        "evaluation_limit": "40x",
        "feature": "40x",
        "limit_exceeded_action": "40x",
        "reset_date": "40x"
    }

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/budgets/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_post_fuzzed_body):
        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/v1/budgets/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_post_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/v1/budgets/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_post()
