# Generated by Skyramp v1.2.0+c41d98f4 on 2026-03-14 10:08:42.870007 -0700 PDT m=+151.160254209
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_feature_summary.py \
# 		--output-dir /Users/mrugeshmaster/git/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/flagsmith-testb/api/tests/scenario_feature_summary_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    projects = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "is_server_key_only": false,
        "name": "feature_standard_test_1",
        "type": "STANDARD"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_1_POST_request_body,
        path_params={"projects": projects}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "is_server_key_only": true,
        "name": "feature_server_key_test_1",
        "type": "STANDARD"
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        path_params={"projects": skyramp.get_response_value(endpoint_1_POST_response, "project")}
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201

    # Request Body
    endpoint_1_POST_2_request_body = r'''{
        "is_server_key_only": false,
        "name": "feature_multivariate_test_1",
        "type": "MULTIVARIATE"
    }'''
    
    # Execute Request
    endpoint_1_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_1_POST_2_request_body,
        path_params={"projects": skyramp.get_response_value(endpoint_1_POST_response, "project")}
    )
    # Generated Assertions
    assert endpoint_1_POST_2_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/summary/",
        method="GET",
        path_params={"projects": skyramp.get_response_value(endpoint_1_POST_response, "project")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    summary_data = endpoint_2_GET_response.json()
    assert "archived" in summary_data
    assert summary_data["archived"] == 0

if __name__ == "__main__":
    test_integration()
