# Generated by Skyramp v1.3.11 on 2026-03-11 14:06:50.79222658 +0000 UTC m=+130.426192788
# Command: skyramp generate contract rest http://localhost:8080/api/v1/budgets/1/reset/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_budget_reset_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params id=1 \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# contract test for /api/v1/budgets/1/reset/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{}'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/budgets/1/reset/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 200

if __name__ == "__main__":
    test_endpoint_post()
