# Generated by Skyramp v1.3.11 on 2026-03-11 13:17:03.11894022 +0000 UTC m=+258.794792502
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_budget_filter_integration.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests/scenario_budget_filter_by_feature_1741698000.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "evaluation_limit": 750,
        "feature": 1,
        "limit_exceeded_action": "disable",
        "reset_date": "2026-04-01"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/budgets/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/budgets/",
        method="GET"
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
