# Generated by Skyramp v1.3.11 on 2026-03-11 13:16:19.442219736 +0000 UTC m=+215.118072028
# Command: skyramp generate contract rest http://localhost:8080/api/v1/budgets/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_budget_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--request-data {"feature":1,"evaluation_limit":500,"limit_exceeded_action":"disable","reset_date":"2026-04-01"} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# contract test for /api/v1/budgets/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
        "evaluation_limit": 500,
        "feature": 1,
        "limit_exceeded_action": "disable",
        "reset_date": "2026-04-01"
    }'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/budgets/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 201

if __name__ == "__main__":
    test_endpoint_post()
