# Generated by Skyramp v1.3.11 on 2026-03-11 14:06:37.02288732 +0000 UTC m=+116.656853528
# Command: skyramp generate contract rest http://localhost:8080/api/v1/budgets/1/status/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_budget_status_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/api/tests \
# 		--overwrite \
# 		--path-params id=1 \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8080"

# contract test for /api/v1/budgets/1/status/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/budgets/1/status/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert endpoint_GET_response.status_code == 200

if __name__ == "__main__":
    test_endpoint_get()
