# Generated by Skyramp v1.3.13 on 2026-03-19 11:14:51.954531658 +0000 UTC m=+134.275422264
# Command: skyramp generate contract rest http://localhost:8000/api/v1/test-validation-endpoint/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output provider_contract_test.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"status":"ok","validation":"SKYR-3647"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/test-validation-endpoint/ GET
def test_test_validation_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_test-validation-endpoint_GET_response_body = r'''{
        "status": "ok",
        "validation": "SKYR-3647"
    }'''

    # Execute Request
    test-validation-endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/test-validation-endpoint/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(test-validation-endpoint_GET_response, "20x")
    assert skyramp.check_schema(test-validation-endpoint_GET_response, expected_test-validation-endpoint_GET_response_body)
    assert skyramp.get_response_value(test-validation-endpoint_GET_response, "status") is not None
    assert skyramp.get_response_value(test-validation-endpoint_GET_response, "validation") is not None


if __name__ == "__main__":
    test_test_validation_endpoint_get()
