# Generated by Skyramp v1.3.13 on 2026-03-16 22:17:04.581895371 +0000 UTC m=+169.280764567
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/segment-rollouts/1/update-percentage/ \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output test_segment_rollout_update_percentage_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--path-params id=1 \
# 		--provider \
# 		--request-data {"rollout_percentage":50} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/segment-rollouts/1/update-percentage/ PATCH
def test_update_percentage_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    update_percentage_PATCH_request_body = r'''{
      "rollout_percentage": 50
    }'''

    # Fuzz strategies
    update_percentage_patch_fuzzed_body = {"rollout_percentage": -10}
    # Fuzz status codes
    expected_update_percentage_patch_status_code = {"rollout_percentage": "40x"}
    # Fuzz status codes for Null values
    expected_update_percentage_patch_null_status_code = {"rollout_percentage": "40x"}

    # Execute Request
    update_percentage_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/segment-rollouts/1/update-percentage/",
        method="PATCH",
        body=update_percentage_PATCH_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(update_percentage_patch_fuzzed_body):
        # Execute Request
        update_percentage_PATCH_response = client.send_request(
            url=URL,
            path="/api/v1/segment-rollouts/1/update-percentage/",
            method="PATCH",
            body=update_percentage_PATCH_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(update_percentage_patch_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_update_percentage_patch_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(update_percentage_patch_fuzzed_body, key) }'
        )

        # Execute Request
        update_percentage_PATCH_response = client.send_request(
            url=URL,
            path="/api/v1/segment-rollouts/1/update-percentage/",
            method="PATCH",
            body=update_percentage_PATCH_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_update_percentage_patch_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_update_percentage_patch()
