# Generated by Skyramp v1.3.13 on 2026-03-16 22:17:04.629860052 +0000 UTC m=+169.328729258
# Command: skyramp generate contract rest http://localhost:8000/api/v1/segment-rollouts/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_segment_rollouts_list_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/segment-rollouts/ GET
def test_segment_rollouts_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    segment_rollouts_GET_response = client.send_request(
        url=URL,
        path="/api/v1/segment-rollouts/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(segment_rollouts_GET_response, "20x")
    first_item = skyramp.get_response_value(segment_rollouts_GET_response, "results.0")
    if first_item is not None:
        assert "rollout_percentage" in first_item
        assert "rollout_strategy" in first_item


if __name__ == "__main__":
    test_segment_rollouts_get()
