# Generated by Skyramp v1.3.13 on 2026-03-16 21:29:48.175221343 +0000 UTC m=+275.352138485
# Command: skyramp generate fuzz rest http://localhost:8080/api/v1/projects/1/features/1/cost-profile/set-cost/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_cost_profile_set_cost_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--path-params project_pk=1,feature_pk=1 \
# 		--provider \
# 		--request-data {"cost_per_evaluation":"0.000100","fixed_monthly_cost":"25.00","cost_category":"compute","currency":"USD"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# fuzz test for /api/v1/projects/1/features/1/cost-profile/set-cost/ POST
def test_set_cost_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    set_cost_POST_request_body = r'''{
      "cost_per_evaluation": "0.000100",
      "fixed_monthly_cost": "25.00",
      "cost_category": "compute",
      "currency": "USD"
    }'''

    # Fuzz strategies
    set_cost_post_fuzzed_body = {
        "cost_category": "0123456789",
        "cost_per_evaluation": "0123456789",
        "currency": "0123456789",
        "fixed_monthly_cost": "0123456789"
    }
    # Fuzz status codes
    expected_set_cost_post_status_code = {
        "cost_category": "40x",
        "cost_per_evaluation": "40x",
        "currency": "40x",
        "fixed_monthly_cost": "40x"
    }
    # Fuzz status codes for Null values
    expected_set_cost_post_null_status_code = {
        "cost_category": "40x",
        "cost_per_evaluation": "40x",
        "currency": "40x",
        "fixed_monthly_cost": "40x"
    }

    # Execute Request
    set_cost_POST_response = client.send_request(
        url=URL,
        path="/api/v1/projects/1/features/1/cost-profile/set-cost/",
        method="POST",
        body=set_cost_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(set_cost_post_fuzzed_body):
        # Execute Request
        set_cost_POST_response = client.send_request(
            url=URL,
            path="/api/v1/projects/1/features/1/cost-profile/set-cost/",
            method="POST",
            body=set_cost_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(set_cost_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_set_cost_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(set_cost_post_fuzzed_body, key) }'
        )

        # Execute Request
        set_cost_POST_response = client.send_request(
            url=URL,
            path="/api/v1/projects/1/features/1/cost-profile/set-cost/",
            method="POST",
            body=set_cost_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_set_cost_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_set_cost_post()
