# Generated by Skyramp v1.3.13 on 2026-03-16 23:07:11.432627624 +0000 UTC m=+160.117212756
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_segment_rollout_cap_at_100.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_segment_rollout_cap_at_100.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/segment-rollouts/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Request Body
    endpoint_3_PATCH_request_body = r'''{
        "rollout_percentage": 90
    }'''
    
    # Execute Request
    endpoint_3_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/segment-rollouts/{segment-rollouts}/update-percentage/",
        method="PATCH",
        body=endpoint_3_PATCH_request_body,
        headers=headers,
        path_params={"segment-rollouts": skyramp.get_response_value(endpoint_1_GET_response, "0.id")}
    )
    # Generated Assertions
    assert endpoint_3_PATCH_response.status_code == 200

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "increment": 20
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/segment-rollouts/{segment-rollouts}/increase/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"segment-rollouts": skyramp.get_response_value(endpoint_3_PATCH_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
