# Generated by Skyramp v1.3.13 on 2026-03-16 23:08:44.003824796 +0000 UTC m=+149.901668930
# Command: skyramp generate contract rest http://localhost:8000/api/v1/usage-metrics/reset/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_usage_metrics_reset_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature_ids":[1,2]} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/usage-metrics/reset/ POST
def test_reset_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    reset_POST_request_body = r'''{
        "feature_ids": [
            1,
            2
        ]
    }'''

    # Execute Request
    reset_POST_response = client.send_request(
        url=URL,
        path="/api/v1/usage-metrics/reset/",
        method="POST",
        body=reset_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert reset_POST_response.status_code == 200


if __name__ == "__main__":
    test_reset_post()
