# Generated by Skyramp v1.3.13 on 2026-03-17 14:52:00.580849593 +0000 UTC m=+207.834973175
# Command: skyramp generate contract rest http://localhost:8000/api/v1/segment-rollouts/1/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_segment_rollout_get_by_id_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--path-params id=1 \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/segment-rollouts/1/ GET
def test_endpoint_1_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL,
        path="/api/v1/segment-rollouts/1/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert "rollout_percentage" in skyramp.get_response_value(endpoint_1_GET_response, "")
    assert "rollout_strategy" in skyramp.get_response_value(endpoint_1_GET_response, "")


if __name__ == "__main__":
    test_endpoint_1_get()
