# Generated by Skyramp v1.3.13 on 2026-03-17 14:52:13.835545577 +0000 UTC m=+221.089669129
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/segment-rollouts/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_segment_rollout_filter_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params min_percentage=50,max_percentage=100 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/segment-rollouts/ GET
def test_segment_rollouts_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Fuzz strategies
    segment_rollouts_get_fuzzed_query = {
        "max_percentage": "100",
        "min_percentage": "50"
    }
    # Fuzz status codes
    expected_segment_rollouts_get_fuzzed_query_status_code = {
        "max_percentage": "40x",
        "min_percentage": "40x"
    }

    # Execute Request
    segment_rollouts_GET_response = client.send_request(
        url=URL,
        path="/api/v1/segment-rollouts/",
        method="GET",
        headers=headers,
        query_params={
            "max_percentage": "100",
            "min_percentage": "50"
        },
        expected_code="20x"
    )

    for key in segment_rollouts_get_fuzzed_query:
        query_params = {
            "max_percentage": "100",
            "min_percentage": "50"
        }

        query_params[key] = segment_rollouts_get_fuzzed_query[key]

        # Execute Request
        segment_rollouts_GET_response = client.send_request(
            url=URL,
            path="/api/v1/segment-rollouts/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_segment_rollouts_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { segment_rollouts_get_fuzzed_query[key] }'
        )

        query_params = {
            "max_percentage": "100",
            "min_percentage": "50"
        }

        query_params[key] = ""

        # Execute Request
        segment_rollouts_GET_response = client.send_request(
            url=URL,
            path="/api/v1/segment-rollouts/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_segment_rollouts_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_segment_rollouts_get()
