# Generated by Skyramp v1.3.13 on 2026-03-16 22:01:31.74017143 +0000 UTC m=+227.984423815
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_health_status_zombie_alerts_detection.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_health_status_zombie_alerts_detection.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "alert_triggered": true,
        "days_since_last_change": 90,
        "environment": 1,
        "evaluation_error_rate": 0,
        "feature": 2,
        "health_score": 20,
        "is_zombie": true,
        "last_evaluated": "2026-01-01T00:00:00Z"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/zombies/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/alerts/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Execute Request
    endpoint_4_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/{health-status}/",
        method="DELETE",
        headers=headers,
        path_params={"health-status": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_4_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
