# Generated by Skyramp v1.3.13 on 2026-03-16 23:07:36.873568538 +0000 UTC m=+151.102263430
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/schedules/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_feature_schedule_validation_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"scheduled_at":"2020-01-01T00:00:00Z","new_enabled_state":true,"created_by":1} \
# 		--response-status-code 400 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/schedules/ POST
def test_schedules_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    schedules_POST_request_body = r'''{
        "created_by": 1,
        "environment": 1,
        "feature": 1,
        "new_enabled_state": true,
        "scheduled_at": "2020-01-01T00:00:00Z"
    }'''

    # Execute Request
    schedules_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/schedules/",
        method="POST",
        body=schedules_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert schedules_POST_response.status_code == 400


if __name__ == "__main__":
    test_schedules_post()
