# Generated by Skyramp v1.3.13 on 2026-03-16 23:07:36.587104134 +0000 UTC m=+150.815799026
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/schedules/pending/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_feature_schedule_pending_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/schedules/pending/ GET
def test_pending_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    pending_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/schedules/pending/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(pending_GET_response, "20x")


if __name__ == "__main__":
    test_pending_get()
