# Generated by Skyramp v1.3.13 on 2026-03-16 22:53:03.87684546 +0000 UTC m=+167.289590541
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_usage_metrics_update_delete_integration.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_usage_metrics_update_delete_lifecycle_20260316.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    environment = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "environment": 1,
        "evaluation_count": 500,
        "feature": 1,
        "period_end": "2026-03-15T00:00:00Z",
        "period_start": "2026-03-01T00:00:00Z",
        "unique_identities_count": 100
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={
            "environment": environment,
            "feature": environment
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_PUT_request_body = r'''{
        "environment": 1,
        "evaluation_count": 2000,
        "feature": 1,
        "period_end": "2026-03-15T00:00:00Z",
        "period_start": "2026-03-01T00:00:00Z",
        "unique_identities_count": 450
    }'''
    
    # Execute Request
    endpoint_2_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/{usage-metrics}/",
        method="PUT",
        body=endpoint_2_PUT_request_body,
        headers=headers,
        path_params={"usage-metrics": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        data_override={
            "environment": skyramp.get_response_value(endpoint_1_POST_response, "environment"),
            "feature": skyramp.get_response_value(endpoint_1_POST_response, "feature")
        }
    )
    # Generated Assertions
    assert endpoint_2_PUT_response.status_code == 200

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/{usage-metrics}/",
        method="DELETE",
        headers=headers,
        path_params={"usage-metrics": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
