# Generated by Skyramp v1.3.13 on 2026-03-16 23:08:56.985161835 +0000 UTC m=+162.883005959
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_usage_metrics_filtering_integration.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_usage_metrics_filtering_workflow_20260316.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "environment": 1,
        "evaluation_count": 750,
        "feature": 1,
        "last_evaluated_at": "2026-03-16T08:00:00Z",
        "period_end": "2026-03-16T00:00:00Z",
        "period_start": "2026-03-01T00:00:00Z",
        "unique_identities_count": 150
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
