# Generated by Skyramp v1.3.13 on 2026-03-16 22:17:11.664402934 +0000 UTC m=+176.363272130
# Command: skyramp generate contract rest http://localhost:8000/api/v1/segment-rollouts/1/increase/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_segment_rollout_increase_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--path-params id=1 \
# 		--provider \
# 		--request-data {"increment":10} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/segment-rollouts/1/increase/ POST
def test_increase_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    increase_POST_request_body = r'''{
        "increment": 10
    }'''

    # Execute Request
    increase_POST_response = client.send_request(
        url=URL,
        path="/api/v1/segment-rollouts/1/increase/",
        method="POST",
        body=increase_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert increase_POST_response.status_code == 200
    assert "rollout_percentage" in skyramp.get_response_value(increase_POST_response, "")


if __name__ == "__main__":
    test_increase_post()
