# Generated by Skyramp v1.3.13 on 2026-03-19 12:33:54.766019242 +0000 UTC m=+195.466591950
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_usage_metrics_unique_constraint_integration_20260319.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_usage_metrics_unique_constraint_conflict_20260319.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "environment": 1,
        "evaluation_count": 500,
        "feature": 1,
        "period_end": "2026-03-31T00:00:00Z",
        "period_start": "2026-03-01T00:00:00Z",
        "unique_identities_count": 50
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "environment": 1,
        "evaluation_count": 999,
        "feature": 1,
        "period_end": "2026-03-31T00:00:00Z",
        "period_start": "2026-03-01T00:00:00Z",
        "unique_identities_count": 99
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers,
        data_override={
            "environment": skyramp.get_response_value(endpoint_1_POST_response, "environment"),
            "feature": skyramp.get_response_value(endpoint_1_POST_response, "feature")
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 400


if __name__ == "__main__":
    test_integration()
