# Generated by Skyramp v1.3.13 on 2026-03-16 23:08:06.271947429 +0000 UTC m=+155.524035653
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_change_request_pending_and_detail.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_change_request_create_pending_detail_1748040100.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "environment": 1,
        "feature": 1,
        "justification": "Disabling this feature to investigate performance regressions in production",
        "requested_change": {
            "enabled": false
        }
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/{change-requests}/",
        method="GET",
        headers=headers,
        path_params={"change-requests": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/{change-requests}/",
        method="GET",
        headers=headers,
        path_params={"change-requests": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_1_response.status_code == 200


if __name__ == "__main__":
    test_integration()
