# Generated by Skyramp v1.3.13 on 2026-03-16 22:47:49.910969149 +0000 UTC m=+197.297840598
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/features/cost-profiles/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_cost_profile_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"cost_per_evaluation":"0.000100","fixed_monthly_cost":"150.00","cost_category":"compute","currency":"USD","notes":"EC2 instance costs for flag evaluation"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/features/cost-profiles/ POST
def test_cost_profiles_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    cost-profiles_POST_request_body = r'''{
      "feature": 1,
      "cost_per_evaluation": "0.000100",
      "fixed_monthly_cost": "150.00",
      "cost_category": "compute",
      "currency": "USD",
      "notes": "EC2 instance costs for flag evaluation"
    }'''
    
    # Fuzz strategies
    cost_profiles_post_fuzzed_body = {
        "cost_category": "0123456789",
        "cost_per_evaluation": "0123456789",
        "currency": "0123456789",
        "feature": -10,
        "fixed_monthly_cost": "0123456789",
        "notes": "0123456789"
    }
    # Fuzz status codes
    expected_cost_profiles_post_status_code = {
        "cost_category": "40x",
        "cost_per_evaluation": "40x",
        "currency": "40x",
        "feature": "40x",
        "fixed_monthly_cost": "40x",
        "notes": "40x"
    }
    # Fuzz status codes for Null values
    expected_cost_profiles_post_null_status_code = {
        "cost_category": "40x",
        "cost_per_evaluation": "40x",
        "currency": "40x",
        "feature": "40x",
        "fixed_monthly_cost": "40x",
        "notes": "40x"
    }

    # Execute Request
    cost-profiles_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/cost-profiles/",
        method="POST",
        body=cost-profiles_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(cost_profiles_post_fuzzed_body):
        # Execute Request
        cost-profiles_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/cost-profiles/",
            method="POST",
            body=cost-profiles_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(cost_profiles_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_cost_profiles_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(cost_profiles_post_fuzzed_body, key) }'
        )

        # Execute Request
        cost-profiles_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/cost-profiles/",
            method="POST",
            body=cost-profiles_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_cost_profiles_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_cost_profiles_post()
