# Generated by Skyramp v1.3.13 on 2026-03-16 21:29:48.134847471 +0000 UTC m=+275.311764603
# Command: skyramp generate contract rest http://localhost:8080/api/v1/projects/1/features/1/cost-profile/set-cost/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_cost_profile_set_cost_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--path-params project_pk=1,feature_pk=1 \
# 		--provider \
# 		--request-data {"cost_per_evaluation":"0.000100","fixed_monthly_cost":"25.00","cost_category":"compute","currency":"USD"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/projects/1/features/1/cost-profile/set-cost/ POST
def test_set_cost_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    set_cost_POST_request_body = r'''{
        "cost_category": "compute",
        "cost_per_evaluation": "0.000100",
        "currency": "USD",
        "fixed_monthly_cost": "25.00"
    }'''

    # Execute Request
    set_cost_POST_response = client.send_request(
        url=URL,
        path="/api/v1/projects/1/features/1/cost-profile/set-cost/",
        method="POST",
        body=set_cost_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(set_cost_POST_response, "20x")


if __name__ == "__main__":
    test_set_cost_post()
