# Generated by Skyramp v1.3.13 on 2026-03-16 22:01:31.890284861 +0000 UTC m=+228.134537216
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/health-status/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_health_status_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"health_score":85,"last_evaluated":"2026-03-16T10:00:00Z","evaluation_error_rate":2.5,"days_since_last_change":3,"is_zombie":false,"alert_triggered":false} \
# 		--response-status-code 201 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/health-status/ POST
def test_health_status_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    health-status_POST_request_body = r'''{
        "alert_triggered": false,
        "days_since_last_change": 3,
        "environment": 1,
        "evaluation_error_rate": 2.5,
        "feature": 1,
        "health_score": 85,
        "is_zombie": false,
        "last_evaluated": "2026-03-16T10:00:00Z"
    }'''

    # Execute Request
    health-status_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/health-status/",
        method="POST",
        body=health-status_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert health-status_POST_response.status_code == 201


if __name__ == "__main__":
    test_health_status_post()
