# Generated by Skyramp v1.3.13 on 2026-03-16 22:53:03.919179124 +0000 UTC m=+167.331924204
# Command: skyramp generate contract rest http://localhost:8000/api/v1/usage-metrics/1/ \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output test_usage_metrics_put_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"evaluation_count":2000,"unique_identities_count":450,"period_start":"2026-03-01T00:00:00Z","period_end":"2026-03-15T00:00:00Z"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/usage-metrics/1/ PUT
def test_endpoint_1_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_PUT_request_body = r'''{
        "environment": 1,
        "evaluation_count": 2000,
        "feature": 1,
        "period_end": "2026-03-15T00:00:00Z",
        "period_start": "2026-03-01T00:00:00Z",
        "unique_identities_count": 450
    }'''

    # Execute Request
    endpoint_1_PUT_response = client.send_request(
        url=URL,
        path="/api/v1/usage-metrics/1/",
        method="PUT",
        body=endpoint_1_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_PUT_response.status_code == 200


if __name__ == "__main__":
    test_endpoint_1_put()
