# Generated by Skyramp v1.3.13 on 2026-03-16 22:17:30.776337101 +0000 UTC m=+148.121958831
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_feature_schedule_lifecycle.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_feature_schedule_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    environment = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "created_by": 1,
        "environment": 1,
        "feature": 1,
        "new_enabled_state": true,
        "scheduled_at": "2027-06-01T00:00:00Z"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/schedules/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"environment": environment}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/schedules/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/schedules/{schedules}/",
        method="GET",
        headers=headers,
        path_params={"schedules": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/schedules/{schedules}/",
        method="GET",
        headers=headers,
        path_params={"schedules": skyramp.get_response_value(endpoint_1_POST_response, "status")}
    )
    # Generated Assertions
    assert endpoint_2_GET_1_response.status_code == 200

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/schedules/{schedules}/",
        method="DELETE",
        headers=headers,
        path_params={"schedules": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
