# Generated by Skyramp v1.3.13 on 2026-03-16 22:52:50.430094351 +0000 UTC m=+149.536499660
# Command: skyramp generate contract rest http://localhost:8000/api/v1/change-requests/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_change_request_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"requested_change":{"enabled":true},"justification":"Business requirement to enable this feature for production rollout"} \
# 		--response-status-code 201 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/change-requests/ POST
def test_change_requests_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    change-requests_POST_request_body = r'''{
        "environment": 1,
        "feature": 1,
        "justification": "Business requirement to enable this feature for production rollout",
        "requested_change": {
            "enabled": true
        }
    }'''

    # Execute Request
    change-requests_POST_response = client.send_request(
        url=URL,
        path="/api/v1/change-requests/",
        method="POST",
        body=change-requests_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert change-requests_POST_response.status_code == 201


if __name__ == "__main__":
    test_change_requests_post()
