# Generated by Skyramp v1.3.13 on 2026-03-16 22:52:50.496835231 +0000 UTC m=+149.603240530
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/change-requests/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_change_request_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"requested_change":{"enabled":true},"justification":"Business requirement to enable this feature for production rollout"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/change-requests/ POST
def test_change_requests_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    change-requests_POST_request_body = r'''{
      "feature": 1,
      "environment": 1,
      "requested_change": {
        "enabled": true
      },
      "justification": "Business requirement to enable this feature for production rollout"
    }'''
    
    # Fuzz strategies
    change_requests_post_fuzzed_body = {
        "environment": -10,
        "feature": -10,
        "justification": "0123456789",
        "requested_change": {"enabled": True}
    }
    # Fuzz status codes
    expected_change_requests_post_status_code = {
        "environment": "40x",
        "feature": "40x",
        "justification": "40x",
        "requested_change": {"enabled": "40x"}
    }
    # Fuzz status codes for Null values
    expected_change_requests_post_null_status_code = {
        "environment": "40x",
        "feature": "40x",
        "justification": "40x",
        "requested_change": {"enabled": "40x"}
    }

    # Execute Request
    change-requests_POST_response = client.send_request(
        url=URL,
        path="/api/v1/change-requests/",
        method="POST",
        body=change-requests_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(change_requests_post_fuzzed_body):
        # Execute Request
        change-requests_POST_response = client.send_request(
            url=URL,
            path="/api/v1/change-requests/",
            method="POST",
            body=change-requests_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(change_requests_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_change_requests_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(change_requests_post_fuzzed_body, key) }'
        )

        # Execute Request
        change-requests_POST_response = client.send_request(
            url=URL,
            path="/api/v1/change-requests/",
            method="POST",
            body=change-requests_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_change_requests_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_change_requests_post()
