# Generated by Skyramp v1.3.13 on 2026-03-16 22:17:03.414570885 +0000 UTC m=+132.252604860
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/dependencies/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_feature_dependency_self_dep_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"required_feature":1,"environment":1,"dependency_type":"requires"} \
# 		--response-status-code 400 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/dependencies/ POST
def test_dependencies_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    dependencies_POST_request_body = r'''{
        "dependency_type": "requires",
        "environment": 1,
        "feature": 1,
        "required_feature": 1
    }'''

    # Execute Request
    dependencies_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/dependencies/",
        method="POST",
        body=dependencies_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert dependencies_POST_response.status_code == 400


if __name__ == "__main__":
    test_dependencies_post()
