# Generated by Skyramp v1.3.13 on 2026-03-16 22:01:31.662317512 +0000 UTC m=+227.906569857
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_health_status_unhealthy_lifecycle.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_health_status_unhealthy_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    feature = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "alert_triggered": false,
        "days_since_last_change": 5,
        "environment": 1,
        "evaluation_error_rate": 15,
        "feature": 1,
        "health_score": 45,
        "is_zombie": false,
        "last_evaluated": "2026-03-10T12:00:00Z"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={
            "environment": feature,
            "feature": feature
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/{health-status}/",
        method="GET",
        headers=headers,
        path_params={"health-status": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200

    # Request Body
    endpoint_3_PUT_request_body = r'''{
        "alert_triggered": true,
        "days_since_last_change": 5,
        "environment": 1,
        "evaluation_error_rate": 35,
        "feature": 1,
        "health_score": 30,
        "is_zombie": false,
        "last_evaluated": "2026-03-16T10:00:00Z"
    }'''
    
    # Execute Request
    endpoint_3_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/{health-status}/",
        method="PUT",
        body=endpoint_3_PUT_request_body,
        headers=headers,
        path_params={"health-status": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        data_override={
            "days_since_last_change": skyramp.get_response_value(endpoint_3_GET_response, "days_since_last_change"),
            "environment": skyramp.get_response_value(endpoint_1_POST_response, "environment"),
            "feature": skyramp.get_response_value(endpoint_1_POST_response, "feature"),
            "last_evaluated": skyramp.get_response_value(endpoint_1_POST_response, "last_check_at")
        }
    )
    # Generated Assertions
    assert endpoint_3_PUT_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/unhealthy/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
