# Generated by Skyramp v1.3.13 on 2026-03-16 23:07:39.140345531 +0000 UTC m=+187.824930654
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/segment-rollouts/1/increase/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_segment_rollout_increase_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--path-params id=1 \
# 		--provider \
# 		--request-data {"increment":10} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/segment-rollouts/1/increase/ POST
def test_increase_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    increase_POST_request_body = r'''{
      "increment": 10
    }'''
    
    # Fuzz strategies
    increase_post_fuzzed_body = {"increment": -10}
    # Fuzz status codes
    expected_increase_post_status_code = {"increment": "40x"}
    # Fuzz status codes for Null values
    expected_increase_post_null_status_code = {"increment": "40x"}

    # Execute Request
    increase_POST_response = client.send_request(
        url=URL,
        path="/api/v1/segment-rollouts/1/increase/",
        method="POST",
        body=increase_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(increase_post_fuzzed_body):
        # Execute Request
        increase_POST_response = client.send_request(
            url=URL,
            path="/api/v1/segment-rollouts/1/increase/",
            method="POST",
            body=increase_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(increase_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_increase_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(increase_post_fuzzed_body, key) }'
        )

        # Execute Request
        increase_POST_response = client.send_request(
            url=URL,
            path="/api/v1/segment-rollouts/1/increase/",
            method="POST",
            body=increase_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_increase_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_increase_post()
