# Generated by Skyramp v1.3.13 on 2026-03-17 15:08:32.136980725 +0000 UTC m=+246.536842735
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_usage_metrics_summary_integration_20260317.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_usage_metrics_summary_verification_20260317.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "environment": 1,
        "evaluation_count": 2500,
        "feature": 1,
        "last_evaluated_at": "2026-03-17T10:00:00Z",
        "period_end": "2026-03-17T00:00:00Z",
        "period_start": "2026-03-10T00:00:00Z",
        "unique_identities_count": 450
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/usage-metrics/summary/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert "total_evaluations" in endpoint_2_GET_response.json()
    assert "total_unique_identities" in endpoint_2_GET_response.json()
    assert "feature_count" in endpoint_2_GET_response.json()


if __name__ == "__main__":
    test_integration()
