# Generated by Skyramp v1.3.13 on 2026-03-16 22:03:22.638179771 +0000 UTC m=+162.869973029
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_feature_dependency_lifecycle.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_feature_dependency_lifecycle_20260316.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    environment = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "dependency_type": "requires",
        "environment": 1,
        "feature": 1,
        "required_feature": 2
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/dependencies/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"environment": environment}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/dependencies/{dependencies}/",
        method="GET",
        headers=headers,
        path_params={"dependencies": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/dependencies/graph/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Execute Request
    endpoint_3_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/dependencies/{dependencies}/",
        method="DELETE",
        headers=headers,
        path_params={"dependencies": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
