# Generated by Skyramp v1.3.13 on 2026-03-17 14:51:57.914283925 +0000 UTC m=+205.168407486
# Command: skyramp generate contract rest http://localhost:8000/api/v1/segment-rollouts/1/update-percentage/ \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output test_segment_rollout_update_percentage_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--path-params id=1 \
# 		--provider \
# 		--request-data {"rollout_percentage":75} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/segment-rollouts/1/update-percentage/ PATCH
def test_update_percentage_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    update-percentage_PATCH_request_body = r'''{
        "rollout_percentage": 75
    }'''

    # Execute Request
    update-percentage_PATCH_response = client.send_request(
        url=URL,
        path="/api/v1/segment-rollouts/1/update-percentage/",
        method="PATCH",
        body=update-percentage_PATCH_request_body,
        headers=headers
    )

    # Generated Assertions
    assert update-percentage_PATCH_response.status_code == 200


if __name__ == "__main__":
    test_update_percentage_patch()
