# Generated by Skyramp v1.3.13 on 2026-03-16 22:17:29.953835672 +0000 UTC m=+194.151780525
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/usage-metrics/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_usage_metrics_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"evaluation_count":100,"unique_identities_count":50,"period_start":"2026-03-09T00:00:00Z","period_end":"2026-03-16T00:00:00Z"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/usage-metrics/ POST
def test_usage_metrics_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    usage-metrics_POST_request_body = r'''{
      "feature": 1,
      "environment": 1,
      "evaluation_count": 100,
      "unique_identities_count": 50,
      "period_start": "2026-03-09T00:00:00Z",
      "period_end": "2026-03-16T00:00:00Z"
    }'''
    
    # Fuzz strategies
    usage_metrics_post_fuzzed_body = {
        "environment": -10,
        "evaluation_count": -10,
        "feature": -10,
        "period_end": "0123456789",
        "period_start": "0123456789",
        "unique_identities_count": -10
    }
    # Fuzz status codes
    expected_usage_metrics_post_status_code = {
        "environment": "40x",
        "evaluation_count": "40x",
        "feature": "40x",
        "period_end": "40x",
        "period_start": "40x",
        "unique_identities_count": "40x"
    }
    # Fuzz status codes for Null values
    expected_usage_metrics_post_null_status_code = {
        "environment": "40x",
        "evaluation_count": "40x",
        "feature": "40x",
        "period_end": "40x",
        "period_start": "40x",
        "unique_identities_count": "40x"
    }

    # Execute Request
    usage-metrics_POST_response = client.send_request(
        url=URL,
        path="/api/v1/usage-metrics/",
        method="POST",
        body=usage-metrics_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(usage_metrics_post_fuzzed_body):
        # Execute Request
        usage-metrics_POST_response = client.send_request(
            url=URL,
            path="/api/v1/usage-metrics/",
            method="POST",
            body=usage-metrics_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(usage_metrics_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_usage_metrics_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(usage_metrics_post_fuzzed_body, key) }'
        )

        # Execute Request
        usage-metrics_POST_response = client.send_request(
            url=URL,
            path="/api/v1/usage-metrics/",
            method="POST",
            body=usage-metrics_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_usage_metrics_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_usage_metrics_post()
