# Generated by Skyramp v1.3.13 on 2026-03-17 14:52:19.929170283 +0000 UTC m=+227.183293834
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_segment_rollout_filter_integration.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_segment_rollout_filter_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/segment-rollouts/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_1_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/segment-rollouts/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_GET_1_response.status_code == 200
    first_item = skyramp.get_response_value(endpoint_1_GET_1_response, "results.0")
    if first_item is not None:
        assert "rollout_percentage" in first_item


if __name__ == "__main__":
    test_integration()
