# Generated by Skyramp v1.3.13 on 2026-03-16 21:15:29.396679663 +0000 UTC m=+232.075287188
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_trait_history_workflow.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_trait_history_workflow_1742137800.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    api = "api"

    # Request Body
    endpoint_5_POST_request_body = r'''{
        "name": "skyramp-test-org-1742137800"
    }'''
    
    # Execute Request
    endpoint_5_POST_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/organisations/",
        method="POST",
        body=endpoint_5_POST_request_body,
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert endpoint_5_POST_response.status_code == 201

    # Request Body
    endpoint_6_POST_request_body = '{"name": "skyramp-test-project-1742137800", "organisation": ' + str(skyramp.get_response_value(endpoint_5_POST_response, "id")) + '}'
    
    # Execute Request
    endpoint_6_POST_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/projects/",
        method="POST",
        body=endpoint_6_POST_request_body,
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert endpoint_6_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = '{"name": "skyramp-test-env-1742137800", "project": ' + str(skyramp.get_response_value(endpoint_6_POST_response, "id")) + '}'
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/environments/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "identifier": "skyramp-identity-1742137800"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/environments/{environments}/identities/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={
            "api": api,
            "environments": skyramp.get_response_value(endpoint_1_POST_response, "api_key")
        }
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "trait_key": "plan",
        "trait_value": "premium"
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/environments/{environments}/identities/{identities}/traits/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        path_params={
            "api": api,
            "environments": skyramp.get_response_value(endpoint_1_POST_response, "api_key"),
            "identities": skyramp.get_response_value(endpoint_2_POST_response, "id")
        }
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 200

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/environments/{environments}/identities/{identities}/trait-history/",
        method="GET",
        headers=headers,
        path_params={
            "api": api,
            "environments": skyramp.get_response_value(endpoint_1_POST_response, "api_key"),
            "identities": skyramp.get_response_value(endpoint_2_POST_response, "id")
        }
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
