# Generated by Skyramp v1.3.13 on 2026-03-16 21:28:44.62986117 +0000 UTC m=+211.806778292
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_feature_cost_tracking_integration.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_feature_cost_tracking_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    project = "1"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "email": "costtest@example.com",
        "first_name": "Cost",
        "last_name": "Tester",
        "password": "TestPass123!"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/auth/users/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "email": "costtest@example.com",
        "password": "TestPass123!"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/auth/login/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "Cost Tracking Org"
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "Cost Tracking Project",
        "organisation": 1
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201

    # Request Body
    endpoint_6_POST_request_body = r'''{
        "default_enabled": true,
        "name": "cost_tracked_feature",
        "project": 1,
        "type": "FLAG"
    }'''
    
    # Execute Request
    endpoint_6_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_6_POST_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(endpoint_4_POST_response, "id")},
        data_override={"project": project}
    )
    # Generated Assertions
    assert endpoint_6_POST_response.status_code == 201

    # Request Body
    endpoint_8_POST_request_body = r'''{
        "cost_category": "compute",
        "cost_per_evaluation": "0.000100",
        "currency": "USD",
        "fixed_monthly_cost": "25.00"
    }'''
    
    # Execute Request
    endpoint_8_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/{features}/cost-profile/set-cost/",
        method="POST",
        body=endpoint_8_POST_request_body,
        headers=headers,
        path_params={
            "features": skyramp.get_response_value(endpoint_6_POST_response, "id"),
            "projects": skyramp.get_response_value(endpoint_4_POST_response, "id")
        }
    )
    # Generated Assertions
    assert endpoint_8_POST_response.status_code == 200

    # Execute Request
    endpoint_7_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/{features}/cost-profile/estimate/",
        method="GET",
        headers=headers,
        path_params={
            "features": skyramp.get_response_value(endpoint_6_POST_response, "id"),
            "projects": skyramp.get_response_value(endpoint_4_POST_response, "id")
        }
    )
    # Generated Assertions
    assert endpoint_7_GET_response.status_code == 200

    # Execute Request
    endpoint_5_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/cost-aggregation/",
        method="GET",
        headers=headers,
        path_params={"projects": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_5_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
