# Generated by Skyramp v1.3.13 on 2026-03-16 21:16:20.10343246 +0000 UTC m=+282.782039996
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/at-time/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_trait_history_at_time_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params timestamp=2026-03-16T00:00:00Z \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/at-time/ GET
def test_at_time_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Fuzz strategies
    at_time_get_fuzzed_query = {"timestamp": "2026-03-16T00:00:00Z"}
    # Fuzz status codes
    expected_at_time_get_fuzzed_query_status_code = {"timestamp": "40x"}

    # Execute Request
    at-time_GET_response = client.send_request(
        url=URL,
        path="/api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/at-time/",
        method="GET",
        headers=headers,
        query_params={"timestamp": "2026-03-16T00:00:00Z"},
        expected_code="20x"
    )

    for key in at_time_get_fuzzed_query:
        query_params = {"timestamp": "2026-03-16T00:00:00Z"}

        query_params[key] = at_time_get_fuzzed_query[key]

        # Execute Request
        at-time_GET_response = client.send_request(
            url=URL,
            path="/api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/at-time/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_at_time_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { at_time_get_fuzzed_query[key] }'
        )

        query_params = {"timestamp": "2026-03-16T00:00:00Z"}

        query_params[key] = ""

        # Execute Request
        at-time_GET_response = client.send_request(
            url=URL,
            path="/api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/at-time/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_at_time_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_at_time_get()
