# Generated by Skyramp v1.3.13 on 2026-03-16 22:47:49.80827415 +0000 UTC m=+197.195145760
# Command: skyramp generate contract rest http://localhost:8000/api/v1/features/cost-profiles/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_cost_profile_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"cost_per_evaluation":"0.000100","fixed_monthly_cost":"150.00","cost_category":"compute","currency":"USD","notes":"EC2 instance costs for flag evaluation"} \
# 		--response-status-code 201 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/features/cost-profiles/ POST
def test_cost_profiles_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    cost-profiles_POST_request_body = r'''{
        "cost_category": "compute",
        "cost_per_evaluation": "0.000100",
        "currency": "USD",
        "feature": 1,
        "fixed_monthly_cost": "150.00",
        "notes": "EC2 instance costs for flag evaluation"
    }'''

    # Execute Request
    cost-profiles_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/cost-profiles/",
        method="POST",
        body=cost-profiles_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert cost-profiles_POST_response.status_code == 201


if __name__ == "__main__":
    test_cost_profiles_post()
