# Generated by Skyramp v1.3.13 on 2026-03-16 22:18:04.528053592 +0000 UTC m=+181.873675292
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/features/schedules/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_feature_schedule_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"scheduled_at":"2027-06-01T00:00:00Z","new_enabled_state":true,"created_by":1} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/features/schedules/ POST
def test_schedules_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    schedules_POST_request_body = r'''{
      "feature": 1,
      "environment": 1,
      "scheduled_at": "2027-06-01T00:00:00Z",
      "new_enabled_state": true,
      "created_by": 1
    }'''
    
    # Fuzz strategies
    schedules_post_fuzzed_body = {
        "created_by": -10,
        "environment": -10,
        "feature": -10,
        "new_enabled_state": True,
        "scheduled_at": "0123456789"
    }
    # Fuzz status codes
    expected_schedules_post_status_code = {
        "created_by": "40x",
        "environment": "40x",
        "feature": "40x",
        "new_enabled_state": "40x",
        "scheduled_at": "40x"
    }
    # Fuzz status codes for Null values
    expected_schedules_post_null_status_code = {
        "created_by": "40x",
        "environment": "40x",
        "feature": "40x",
        "new_enabled_state": "40x",
        "scheduled_at": "40x"
    }

    # Execute Request
    schedules_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/schedules/",
        method="POST",
        body=schedules_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(schedules_post_fuzzed_body):
        # Execute Request
        schedules_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/schedules/",
            method="POST",
            body=schedules_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(schedules_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_schedules_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(schedules_post_fuzzed_body, key) }'
        )

        # Execute Request
        schedules_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/schedules/",
            method="POST",
            body=schedules_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_schedules_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_schedules_post()
