# Generated by Skyramp v1.3.13 on 2026-03-16 21:18:00.239772778 +0000 UTC m=+399.241695281
# Command: skyramp generate fuzz rest http://localhost:8080/api/v1/features/health-status/configure-alerts/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_feature_health_configure_alerts_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"environment_id":1,"alert_enabled":true} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# fuzz test for /api/v1/features/health-status/configure-alerts/ POST
def test_configure_alerts_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    configure_alerts_POST_request_body = r'''{
      "environment_id": 1,
      "alert_enabled": true
    }'''
    
    # Fuzz strategies
    configure_alerts_post_fuzzed_body = {
        "alert_enabled": True,
        "environment_id": -10
    }
    # Fuzz status codes
    expected_configure_alerts_post_status_code = {
        "alert_enabled": "40x",
        "environment_id": "40x"
    }
    # Fuzz status codes for Null values
    expected_configure_alerts_post_null_status_code = {
        "alert_enabled": "40x",
        "environment_id": "40x"
    }

    # Execute Request
    configure_alerts_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/health-status/configure-alerts/",
        method="POST",
        body=configure_alerts_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(configure_alerts_post_fuzzed_body):
        # Execute Request
        configure_alerts_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/health-status/configure-alerts/",
            method="POST",
            body=configure_alerts_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(configure_alerts_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_configure_alerts_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(configure_alerts_post_fuzzed_body, key) }'
        )

        # Execute Request
        configure_alerts_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/health-status/configure-alerts/",
            method="POST",
            body=configure_alerts_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_configure_alerts_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_configure_alerts_post()
