# Generated by Skyramp v1.3.13 on 2026-03-16 21:16:51.136261782 +0000 UTC m=+330.138184296
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_feature_health_alert_flow.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_feature_health_alert_flow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    project = "1"

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "Health Monitor Org"
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/organisations/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201

    # Request Body
    endpoint_5_POST_request_body = r'''{
        "name": "Health Monitor Project",
        "organisation": 1
    }'''

    # Execute Request
    endpoint_5_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/",
        method="POST",
        body=endpoint_5_POST_request_body,
        headers=headers,
        data_override={"organisation": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_5_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Development",
        "project": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/environments/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"project": skyramp.get_response_value(endpoint_5_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_6_POST_request_body = r'''{
        "description": "Feature flag for health monitoring test",
        "name": "health_monitored_flag",
        "project": 1,
        "type": "FLAG"
    }'''
    
    # Execute Request
    endpoint_6_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/projects/{projects}/features/",
        method="POST",
        body=endpoint_6_POST_request_body,
        headers=headers,
        path_params={"projects": skyramp.get_response_value(endpoint_5_POST_response, "id")},
        data_override={"project": skyramp.get_response_value(endpoint_1_POST_response, "project")}
    )
    # Generated Assertions
    assert endpoint_6_POST_response.status_code == 201

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "alert_enabled": true,
        "environment_id": 1
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/configure-alerts/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers,
        data_override={"environment_id": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/active-alerts/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
