# Generated by Skyramp v1.3.13 on 2026-03-16 22:03:49.774982792 +0000 UTC m=+190.006776060
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/features/dependencies/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_feature_dependency_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"required_feature":2,"environment":1,"dependency_type":"requires"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/features/dependencies/ POST
def test_dependencies_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    dependencies_POST_request_body = r'''{
      "feature": 1,
      "required_feature": 2,
      "environment": 1,
      "dependency_type": "requires"
    }'''
    
    # Fuzz strategies
    dependencies_post_fuzzed_body = {
        "dependency_type": "0123456789",
        "environment": -10,
        "feature": -10,
        "required_feature": -10
    }
    # Fuzz status codes
    expected_dependencies_post_status_code = {
        "dependency_type": "40x",
        "environment": "40x",
        "feature": "40x",
        "required_feature": "40x"
    }
    # Fuzz status codes for Null values
    expected_dependencies_post_null_status_code = {
        "dependency_type": "40x",
        "environment": "40x",
        "feature": "40x",
        "required_feature": "40x"
    }

    # Execute Request
    dependencies_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/dependencies/",
        method="POST",
        body=dependencies_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(dependencies_post_fuzzed_body):
        # Execute Request
        dependencies_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/dependencies/",
            method="POST",
            body=dependencies_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(dependencies_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_dependencies_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(dependencies_post_fuzzed_body, key) }'
        )

        # Execute Request
        dependencies_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/dependencies/",
            method="POST",
            body=dependencies_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_dependencies_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_dependencies_post()
