# Generated by Skyramp v1.3.13 on 2026-03-16 23:06:59.601668888 +0000 UTC m=+126.185251893
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_cost_profile_delete.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_cost_profile_delete_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "cost_category": "network",
        "cost_per_evaluation": "0.000050",
        "currency": "USD",
        "feature": 1,
        "fixed_monthly_cost": "100.00",
        "notes": "Network egress costs for flag distribution"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/cost-profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/cost-profiles/{cost-profiles}/",
        method="DELETE",
        headers=headers,
        path_params={"cost-profiles": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 204

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/cost-profiles/{cost-profiles}/",
        method="GET",
        headers=headers,
        path_params={"cost-profiles": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
