# Generated by Skyramp v1.3.13 on 2026-03-16 22:47:26.272839986 +0000 UTC m=+173.659711435
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_cost_profile_lifecycle.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_cost_profile_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    feature = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "cost_category": "compute",
        "cost_per_evaluation": "0.000100",
        "currency": "USD",
        "feature": 1,
        "fixed_monthly_cost": "150.00",
        "notes": "EC2 instance costs for flag evaluation"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/cost-profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"feature": feature}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/cost-profiles/{cost-profiles}/",
        method="GET",
        headers=headers,
        path_params={"cost-profiles": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200

    # Request Body
    endpoint_3_PUT_request_body = r'''{
        "cost_category": "storage",
        "cost_per_evaluation": "0.000200",
        "currency": "USD",
        "feature": 1,
        "fixed_monthly_cost": "275.50",
        "notes": "Updated S3 storage costs for flag evaluation"
    }'''
    
    # Execute Request
    endpoint_3_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/cost-profiles/{cost-profiles}/",
        method="PUT",
        body=endpoint_3_PUT_request_body,
        headers=headers,
        path_params={"cost-profiles": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        data_override={
            "currency": skyramp.get_response_value(endpoint_3_GET_response, "currency"),
            "feature": skyramp.get_response_value(endpoint_1_POST_response, "feature")
        }
    )
    # Generated Assertions
    assert endpoint_3_PUT_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/cost-profiles/summary/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
