# Generated by Skyramp v1.3.13 on 2026-03-16 22:01:32.028455693 +0000 UTC m=+228.272708048
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/features/health-status/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_health_status_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"health_score":75,"last_evaluated":"2026-03-16T10:00:00Z","evaluation_error_rate":10.0,"days_since_last_change":2,"is_zombie":false,"alert_triggered":false} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/features/health-status/ POST
def test_health_status_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    health-status_POST_request_body = r'''{
      "feature": 1,
      "environment": 1,
      "health_score": 75,
      "last_evaluated": "2026-03-16T10:00:00Z",
      "evaluation_error_rate": 10.0,
      "days_since_last_change": 2,
      "is_zombie": false,
      "alert_triggered": false
    }'''
    
    # Fuzz strategies
    health_status_post_fuzzed_body = {
        "alert_triggered": True,
        "days_since_last_change": -10,
        "environment": -10,
        "evaluation_error_rate": -10,
        "feature": -10,
        "health_score": -10,
        "is_zombie": True,
        "last_evaluated": "0123456789"
    }
    # Fuzz status codes
    expected_health_status_post_status_code = {
        "alert_triggered": "40x",
        "days_since_last_change": "40x",
        "environment": "40x",
        "evaluation_error_rate": "40x",
        "feature": "40x",
        "health_score": "40x",
        "is_zombie": "40x",
        "last_evaluated": "40x"
    }
    # Fuzz status codes for Null values
    expected_health_status_post_null_status_code = {
        "alert_triggered": "40x",
        "days_since_last_change": "40x",
        "environment": "40x",
        "evaluation_error_rate": "40x",
        "feature": "40x",
        "health_score": "40x",
        "is_zombie": "40x",
        "last_evaluated": "40x"
    }

    # Execute Request
    health-status_POST_response = client.send_request(
        url=URL,
        path="/api/v1/features/health-status/",
        method="POST",
        body=health-status_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(health_status_post_fuzzed_body):
        # Execute Request
        health-status_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/health-status/",
            method="POST",
            body=health-status_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(health_status_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_health_status_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(health_status_post_fuzzed_body, key) }'
        )

        # Execute Request
        health-status_POST_response = client.send_request(
            url=URL,
            path="/api/v1/features/health-status/",
            method="POST",
            body=health-status_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_health_status_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_health_status_post()
