# Generated by Skyramp v1.3.13 on 2026-03-16 21:59:36.487401904 +0000 UTC m=+223.258723357
# Command: skyramp generate fuzz rest http://localhost:8080/api/v1/environments/1/trait-history/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_trait_history_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params identity_id=1,trait_key=subscription_tier,from_date=2024-01-01T00:00:00Z,to_date=2024-12-31T23:59:59Z \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# fuzz test for /api/v1/environments/1/trait-history/ GET
def test_trait_history_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Fuzz strategies
    trait_history_get_fuzzed_query = {
        "from_date": "2024-01-01T00:00:00Z",
        "identity_id": "1",
        "to_date": "2024-12-31T23:59:59Z",
        "trait_key": "subscription_tier"
    }
    # Fuzz status codes
    expected_trait_history_get_fuzzed_query_status_code = {
        "from_date": "40x",
        "identity_id": "40x",
        "to_date": "40x",
        "trait_key": "40x"
    }

    # Execute Request
    trait-history_GET_response = client.send_request(
        url=URL,
        path="/api/v1/environments/1/trait-history/",
        method="GET",
        headers=headers,
        query_params={
            "from_date": "2024-01-01T00:00:00Z",
            "identity_id": "1",
            "to_date": "2024-12-31T23:59:59Z",
            "trait_key": "subscription_tier"
        },
        expected_code="20x"
    )

    for key in trait_history_get_fuzzed_query:
        query_params = {
            "from_date": "2024-01-01T00:00:00Z",
            "identity_id": "1",
            "to_date": "2024-12-31T23:59:59Z",
            "trait_key": "subscription_tier"
        }

        query_params[key] = trait_history_get_fuzzed_query[key]

        # Execute Request
        trait-history_GET_response = client.send_request(
            url=URL,
            path="/api/v1/environments/1/trait-history/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_trait_history_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { trait_history_get_fuzzed_query[key] }'
        )

        query_params = {
            "from_date": "2024-01-01T00:00:00Z",
            "identity_id": "1",
            "to_date": "2024-12-31T23:59:59Z",
            "trait_key": "subscription_tier"
        }

        query_params[key] = ""

        # Execute Request
        trait-history_GET_response = client.send_request(
            url=URL,
            path="/api/v1/environments/1/trait-history/",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_trait_history_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_trait_history_get()
