# Generated by Skyramp v1.3.13 on 2026-03-16 22:17:30.05663106 +0000 UTC m=+194.254575913
# Command: skyramp generate contract rest http://localhost:8000/api/v1/usage-metrics/summary/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_usage_metrics_summary_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/usage-metrics/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v1/usage-metrics/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 200


if __name__ == "__main__":
    test_summary_get()
