# Generated by Skyramp v1.3.13 on 2026-03-16 23:07:39.920766503 +0000 UTC m=+129.172854737
# Command: skyramp generate contract rest http://localhost:8000/api/v1/change-requests/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_change_request_list_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/change-requests/ GET
def test_change_requests_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    change-requests_GET_response = client.send_request(
        url=URL,
        path="/api/v1/change-requests/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert change-requests_GET_response.status_code == 200


if __name__ == "__main__":
    test_change_requests_get()
