# Generated by Skyramp v1.3.13 on 2026-03-17 15:09:06.217534355 +0000 UTC m=+280.617396366
# Command: skyramp generate contract rest http://localhost:8000/api/v1/usage-metrics/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_usage_metrics_period_validation_contract_20260317.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"evaluation_count":100,"unique_identities_count":10,"period_start":"2026-03-17T00:00:00Z","period_end":"2026-03-10T00:00:00Z"} \
# 		--response-status-code 400 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/usage-metrics/ POST
def test_usage_metrics_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    usage-metrics_POST_request_body = r'''{
        "environment": 1,
        "evaluation_count": 100,
        "feature": 1,
        "period_end": "2026-03-10T00:00:00Z",
        "period_start": "2026-03-17T00:00:00Z",
        "unique_identities_count": 10
    }'''

    # Execute Request
    usage-metrics_POST_response = client.send_request(
        url=URL,
        path="/api/v1/usage-metrics/",
        method="POST",
        body=usage-metrics_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert usage-metrics_POST_response.status_code == 400


if __name__ == "__main__":
    test_usage_metrics_post()
