# Generated by Skyramp v1.3.13 on 2026-03-16 22:53:03.98378288 +0000 UTC m=+167.396527960
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/usage-metrics/1/ \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output test_usage_metrics_put_fuzz.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"feature":1,"environment":1,"evaluation_count":2000,"unique_identities_count":450,"period_start":"2026-03-01T00:00:00Z","period_end":"2026-03-15T00:00:00Z"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# fuzz test for /api/v1/usage-metrics/1/ PUT
def test_endpoint_1_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_PUT_request_body = r'''{
      "feature": 1,
      "environment": 1,
      "evaluation_count": 2000,
      "unique_identities_count": 450,
      "period_start": "2026-03-01T00:00:00Z",
      "period_end": "2026-03-15T00:00:00Z"
    }'''
    
    # Fuzz strategies
    endpoint_1_put_fuzzed_body = {
        "environment": -10,
        "evaluation_count": -10,
        "feature": -10,
        "period_end": "0123456789",
        "period_start": "0123456789",
        "unique_identities_count": -10
    }
    # Fuzz status codes
    expected_endpoint_1_put_status_code = {
        "environment": "40x",
        "evaluation_count": "40x",
        "feature": "40x",
        "period_end": "40x",
        "period_start": "40x",
        "unique_identities_count": "40x"
    }
    # Fuzz status codes for Null values
    expected_endpoint_1_put_null_status_code = {
        "environment": "40x",
        "evaluation_count": "40x",
        "feature": "40x",
        "period_end": "40x",
        "period_start": "40x",
        "unique_identities_count": "40x"
    }

    # Execute Request
    endpoint_1_PUT_response = client.send_request(
        url=URL,
        path="/api/v1/usage-metrics/1/",
        method="PUT",
        body=endpoint_1_PUT_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_1_put_fuzzed_body):
        # Execute Request
        endpoint_1_PUT_response = client.send_request(
            url=URL,
            path="/api/v1/usage-metrics/1/",
            method="PUT",
            body=endpoint_1_PUT_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_1_put_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_1_put_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_1_put_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_1_PUT_response = client.send_request(
            url=URL,
            path="/api/v1/usage-metrics/1/",
            method="PUT",
            body=endpoint_1_PUT_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_1_put_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_1_put()
