# Generated by Skyramp v1.3.13 on 2026-03-16 21:16:09.262544412 +0000 UTC m=+271.941151937
# Command: skyramp generate contract rest http://localhost:8000/api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_trait_history_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/ GET
def test_trait_history_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    trait-history_GET_response = client.send_request(
        url=URL,
        path="/api/v1/environments/ser.skyramptest1742137800/identities/7001/trait-history/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(trait-history_GET_response, "20x")


if __name__ == "__main__":
    test_trait_history_get()
