# Generated by Skyramp v1.3.13 on 2026-03-16 23:07:37.150394842 +0000 UTC m=+165.286014080
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_health_status_query_param_filtering.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_health_status_query_param_filtering.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "alert_triggered": false,
        "days_since_last_change": 7,
        "environment": 1,
        "evaluation_error_rate": 5,
        "feature": 1,
        "health_score": 50,
        "is_zombie": false,
        "last_evaluated": "2026-03-16T10:00:00Z"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_1_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/features/health-status/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_GET_1_response.status_code == 200


if __name__ == "__main__":
    test_integration()
