# Generated by Skyramp v1.3.13 on 2026-03-18 17:02:12.632660677 +0000 UTC m=+176.838193366
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_change_request_reject_double_prevention_full.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_scenario_change_request_reject_double_prevention_1748041000.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "environment": 1,
        "feature": 1,
        "justification": "Rolling back this feature due to performance concerns in production",
        "requested_change": {
            "enabled": false
        }
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "review_comment": "Rejected - insufficient performance data provided"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/{change-requests}/reject/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"change-requests": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200

    # Request Body
    endpoint_2_POST_1_request_body = r'''{
        "review_comment": "Attempting to reject again"
    }'''
    
    # Execute Request
    endpoint_2_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/{change-requests}/reject/",
        method="POST",
        body=endpoint_2_POST_1_request_body,
        headers=headers,
        path_params={"change-requests": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_1_response.status_code == 400


if __name__ == "__main__":
    test_integration()
