# Generated by Skyramp v1.3.13 on 2026-03-16 21:18:00.138394509 +0000 UTC m=+399.140317012
# Command: skyramp generate contract rest http://localhost:8080/api/v1/features/health-status/project-report/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_feature_health_project_report_contract.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/v1/features/health-status/project-report/ GET
def test_project_report_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    project_report_GET_response = client.send_request(
        url=URL,
        path="/api/v1/features/health-status/project-report/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(project_report_GET_response, "20x")


if __name__ == "__main__":
    test_project_report_get()
