# Generated by Skyramp v1.3.13 on 2026-03-16 21:59:36.326546206 +0000 UTC m=+223.097867649
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_trait_history_integration.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_trait_history_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    api = "api"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/environments/",
        method="GET",
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/environments/{environments}/trait-history/",
        method="GET",
        headers=headers,
        path_params={
            "api": api,
            "environments": skyramp.get_response_value(endpoint_1_GET_response, "results.0.id")
        }
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/{api}/v1/environments/{environments}/trait-history/{trait-history}/",
        method="GET",
        headers=headers,
        path_params={
            "api": api,
            "environments": skyramp.get_response_value(endpoint_1_GET_response, "results.0.id"),
            "trait-history": skyramp.get_response_value(endpoint_2_GET_response, "results.0.id")
        }
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
