# Generated by Skyramp v1.3.13 on 2026-03-17 15:06:16.033117767 +0000 UTC m=+200.149343850
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_change_request_double_approve_prevention.py \
# 		--output-dir /home/runner/work/flagsmith-testb/flagsmith-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/flagsmith-testb/flagsmith-testb/tests/scenario_change_request_double_approve_prevention_1748040200.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "environment": 1,
        "feature": 1,
        "justification": "Enabling feature flag for enterprise production rollout approval test",
        "requested_change": {
            "enabled": true
        }
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "review_comment": "Approved - meets enterprise requirements for production rollout"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/{change-requests}/approve/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"change-requests": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200

    # Request Body
    endpoint_2_POST_1_request_body = r'''{
        "review_comment": "Attempting to approve again"
    }'''
    
    # Execute Request
    endpoint_2_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/change-requests/{change-requests}/approve/",
        method="POST",
        body=endpoint_2_POST_1_request_body,
        headers=headers,
        path_params={"change-requests": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_1_response.status_code == 400


if __name__ == "__main__":
    test_integration()
