# -*- coding: utf-8 -*-
# Generated by Django 5.1 on 2026-03-11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('evaluation_limit', models.IntegerField(
                    validators=[django.core.validators.MinValueValidator(1)],
                    help_text='Maximum number of evaluations allowed per month'
                )),
                ('current_count', models.IntegerField(
                    default=0,
                    validators=[django.core.validators.MinValueValidator(0)],
                    help_text='Current evaluation count for this period'
                )),
                ('reset_date', models.DateField(
                    help_text='Date when the counter resets (next month)'
                )),
                ('limit_exceeded_action', models.CharField(
                    max_length=20,
                    choices=[('disable', 'Disable Feature'), ('alert', 'Send Alert Only')],
                    default='alert',
                    help_text='Action to take when limit is exceeded'
                )),
                ('limit_exceeded', models.BooleanField(
                    default=False,
                    help_text='Whether the limit has been exceeded in the current period'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='budget',
                    to='features.feature',
                    help_text='Feature this budget applies to'
                )),
            ],
            options={
                'db_table': 'features_featurebudget',
                'ordering': ['-created_at'],
            },
        ),
    ]
