# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0065_make_feature_value_size_configurable'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresegment',
            name='rollout_percentage',
            field=models.IntegerField(
                default=100,
                help_text='Percentage of segment users to include in rollout (0-100)'
            ),
        ),
        migrations.AddField(
            model_name='featuresegment',
            name='rollout_strategy',
            field=models.CharField(
                choices=[('random', 'Random'), ('consistent_hash', 'Consistent Hash')],
                default='random',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='historicalfeaturesegment',
            name='rollout_percentage',
            field=models.IntegerField(
                default=100,
                help_text='Percentage of segment users to include in rollout (0-100)'
            ),
        ),
        migrations.AddField(
            model_name='historicalfeaturesegment',
            name='rollout_strategy',
            field=models.CharField(
                choices=[('random', 'Random'), ('consistent_hash', 'Consistent Hash')],
                default='random',
                max_length=20
            ),
        ),
    ]
